## Libraries

In [1]:
#import libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
#load data
def load_data(df):
    return pd.read_csv(file_path)

In [3]:
file_path = '../data/raw/flight_df (2).csv'

df = load_data(file_path)
df.head()

,Age,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,Ease of Online booking,Gate location,Food and drink,Online boarding,Seat comfort,...,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,Gender_Male,Loyal Customer,Business Travel,satisfied
0,26,3,2062,2,3,3,3,2,2,2,...,3,3,3,2,0,0,0,1,1,0
1,52,3,680,5,5,5,5,3,4,4,...,4,4,4,4,18,2,0,1,1,1
2,28,1,188,3,5,3,4,3,3,3,...,4,4,5,3,0,0,1,1,0,0
3,54,3,453,3,5,5,5,3,4,4,...,3,4,3,1,91,80,0,1,1,0
4,40,1,775,4,3,3,3,4,4,4,...,3,3,3,4,0,0,1,1,1,0

## EDA

In [4]:
def explore_data(df):
    number_rows = df.shape[0]
    number_features = df.shape[1]
    data_types = df.dtypes

    print(f'Number of rows: {number_rows}')
    print(f'\nNumber of columns: {number_features}')
    print(f'\nData types: ')
    print(data_types)

explore_data(df)

Number of rows: 20000

Number of columns: 23

Data types:
Age                                  int64
Class                                int64
Flight Distance                      int64
Inflight wifi service                int64
Departure/Arrival time convenient    int64
Ease of Online booking               int64
Gate location                        int64
Food and drink                       int64
Online boarding                      int64
Seat comfort                         int64
Inflight entertainment               int64
On-board service                     int64
Leg room service                     int64
Baggage handling                     int64
Checkin service                      int64
Inflight service                     int64
Cleanliness                          int64
Departure Delay in Minutes           int64
Arrival Delay in Minutes             int64
Gender_Male                          int64
Loyal Customer                       int64
Business Travel                      int64
satisfied                            int64
dtype: object

In [5]:
#functions to perform EDA
def perform_eda(df):
    duplicates = df.duplicated().sum()
    missing_values = df.isna().sum()

    print(f'Number of Duplicate Rows: {duplicates}')
    print(f'\nNumber of Missing Values: {missing_values}')

perform_eda(df)

Number of Duplicate Rows: 0

Number of Missing Values: Age                                  0
Class                                0
Flight Distance                      0
Inflight wifi service                0
Departure/Arrival time convenient    0
Ease of Online booking               0
Gate location                        0
Food and drink                       0
Online boarding                      0
Seat comfort                         0
Inflight entertainment               0
On-board service                     0
Leg room service                     0
Baggage handling                     0
Checkin service                      0
Inflight service                     0
Cleanliness                          0
Departure Delay in Minutes           0
Arrival Delay in Minutes             0
Gender_Male                          0
Loyal Customer                       0
Business Travel                      0
satisfied                            0
dtype: int64

In [6]:
#summary statistics
statistics = df.describe().T
statistics

,count,mean,std,min,25%,50%,75%,max
Age,20000.0,39.47725,15.108901,7.0,27.0,40.0,51.0,85.0
Class,20000.0,2.02780,0.963054,1.0,1.0,2.0,3.0,3.0
Flight Distance,20000.0,1188.54800,1001.136957,31.0,414.0,842.0,1733.0,4983.0
Inflight wifi service,20000.0,2.72795,1.326886,0.0,2.0,3.0,4.0,5.0
Departure/Arrival time convenient,20000.0,3.05610,1.531134,0.0,2.0,3.0,4.0,5.0
Ease of Online booking,20000.0,2.75110,1.396799,0.0,2.0,3.0,4.0,5.0
Gate location,20000.0,2.97135,1.279575,0.0,2.0,3.0,4.0,5.0
Food and drink,20000.0,3.20210,1.332383,0.0,2.0,3.0,4.0,5.0
Online boarding,20000.0,3.25530,1.348485,0.0,2.0,3.0,4.0,5.0
Seat comfort,20000.0,3.43910,1.323434,1.0,2.0,4.0,5.0,5.0
Inflight entertainment,20000.0,3.34910,1.333348,0.0,2.0,4.0,4.0,5.0
On-board service,20000.0,3.38535,1.278451,0.0,2.0,4.0,4.0,5.0
Leg room service,20000.0,3.35085,1.316602,0.0,2.0,4.0,4.0,5.0
Baggage handling,20000.0,3.62365,1.186837,1.0,3.0,4.0,5.0,5.0
Checkin service,20000.0,3.30285,1.259131,1.0,3.0,3.0,4.0,5.0
Inflight service,20000.0,3.63555,1.184017,0.0,3.0,4.0,5.0,5.0
Cleanliness,20000.0,3.28265,1.311734,0.0,2.0,3.0,4.0,5.0
Departure Delay in Minutes,20000.0,14.31835,36.451829,0.0,0.0,0.0,12.0,1305.0
Arrival Delay in Minutes,20000.0,14.69825,36.899857,0.0,0.0,0.0,13.0,1280.0
Gender_Male,20000.0,0.49065,0.499925,0.0,0.0,0.0,1.0,1.0
Loyal Customer,20000.0,0.81785,0.385978,0.0,1.0,1.0,1.0,1.0
Business Travel,20000.0,0.68790,0.463362,0.0,0.0,1.0,1.0,1.0
satisfied,20000.0,0.43305,0.495510,0.0,0.0,0.0,1.0,1.0

In [9]:
#function to check all unique values and anomalies

def check_col_values(df):
    print('Check all columns for anomalies \n')

    #loop throguh each column i nthe data frame
    for column_name in df.columns:
        print(f'Unique Values in {column_name}')
        print(df[column_name].unique())
        print('\n')

check_col_values(df)

Check all columns for anomalies

Unique Values in Age
[26 52 28 54 40 79 41 24 49 59 21 57 25 22 29 48  9 30 42 17 32 44 27 43
 46 37 53 23 12 33 10  7 15 65 20 34 31 39 56  8 60 36 69 58 62 51 47 16
 63 38 72 70 64 18 71 35 45 68 55 11 67 14 19 50 66 61 13 77 80 85 73 75
 74 78 76]


Unique Values in Class
[3 1 2]


Unique Values in Flight Distance
[2062  680  188 ... 3504 2875 1515]


Unique Values in Inflight wifi service
[2 5 3 4 0 1]


Unique Values in Departure/Arrival time convenient
[3 5 1 4 0 2]


Unique Values in Ease of Online booking
[3 5 1 2 0 4]


Unique Values in Gate location
[3 5 4 1 2 0]


Unique Values in Food and drink
[2 3 4 5 1 0]


Unique Values in Online boarding
[2 4 3 0 5 1]


Unique Values in Seat comfort
[2 4 3 5 1]


Unique Values in Inflight entertainment
[2 4 3 5 1 0]


Unique Values in On-board service
[3 4 1 5 2 0]


Unique Values in Leg room service
[3 4 1 2 5 0]


Unique Values in Baggage handling
[3 4 5 1 2]


Unique Values in Checkin service
[3 4 2 5 1]


Unique Values in Inflight service
[3 4 5 2 1 0]


Unique Values in Cleanliness
[2 4 3 1 5 0]


Unique Values in Departure Delay in Minutes
[   0   18   91    2    1    4    9    5   11   20   40    3   26    7
   43   10   83   15   48   31   32   14   51   65  164   28   54   21
    6   53   99   24   12   84  118   22   66   63   16   35   69    8
  104   33   19   29   77  394   13   45  127   67   49  112   25   86
   30  138   17  174  139   96   94   46   38   27  165   78   39   23
  189   59  151   34  496   89  145   72  266   55   37  315   95   90
  121  128   98   62   61   42   52  129   56   70  163   71  100  184
   73   87  136  355  178   82   80  116   41  106  210   97   36  185
   57  115  157  108   47   50  230  105  140   60  133  274   92  146
   58   93  111  250   79   81  122   68  158   64  113  190  290  257
  114  102  202  117  123  365  120   44  141  306  183  239 1305  148
  426   75  282  168  438   76  219  288   74   85  291  188  223  153
  103  254  132  199  126  193  107  156  180  209  172  381  171  241
  154  130  101  296  205  243  134  292  221  327  295  235  124   88
  125  142  176  152  186  204  280  135  276  173  119  147  279  131
  297  231  109  179  110  226  162  215  195  208  143  244  170  268
  211  263  160  360  175  150  410  196  169  149  177  200  236  217
  201  159  253  182  197  319  167  423  301  181  287  222  155  187
  339  358  341  334  216  294  228  286  161  337  264  245  318  194
  412  144  255  259  247  207  357  348  267  137  519  300  328  234
  463  242  248  246  192  371  389  336  166  198  203  275  338  232
  240  258]


Unique Values in Arrival Delay in Minutes
[   0    2   80   13   34    3    9   28   43    7   19   35   18    4
   84   10    5   29    6   44   67  143   24   48    1   53   38   30
   33   14   50   92   20  129   77  127   21   49   56  116   27   99
  114   25   26    8   93  383   23   91   64   58   11   47   61   15
   36  135   40   17   81  106  180  123  109   89   57  131   12  162
   70   32   42  165   46   86   16  150  470  138   76  108  270   31
   37  302   52   45   71  137   59   63   51   22  102  152   55  155
  119  173   41  385   65  194   54  342  103   62  145   83  206   72
  118  174   94   90  183  229  111   39  264  146  161   66   97   98
  156   82  107   88  125  147  104   95   74   69  186   75  279  246
  115  207  121   79  112  139  278  134  193  100  181  226 1280   78
  307  427   73  255  438  237   87   68  117  310   60  203  212  154
  254  130  192  124  196  175  122  198  200  113  228  149  163  353
  167   85  261  101  286  201  256  331  252  128  303  274  110  235
  190  136  160   96  188  355  257  142  262  169  171  299  144  242
  120  126  293  290  218  140  220  276  236  185  208  151  326  239
  179  191  159  105  184  216  132  347  157  397  133  263  170  172
  204  244  164  295  403  294  178  243  177  141  224  158  319  346
  334  213  214  409  209  284  283  199  240  217  317  330  222  166
  245  313  153  205  459  357  238  362  195  189  329  287  187  148
  168  516  404  253  503  176  305  247  339  420  327  202  281  232
  318  369  250]


Unique Values in Gender_Male
[0 1]


Unique Values in Loyal Customer
[1 0]


Unique Values in Business Travel
[1 0]


Unique Values in satisfied
[0 1]